### ISSUE TITLE
Missing math file.

### ISSUE THREAD

**Issue by hickerson** [UCNA/main#4]
RootUtils/PointCloudHistogram.cc:3:30: fatal error: Math/QuasiRandom.h: No such file or directory
compilation terminated.

I seems to be a file in older versions or root.

**Comment by mpmendenhall** [comment]
I think the quasirandom generators are part of the “mathmore” optional component of ROOT; make sure “mathmore” is turned on in your ROOT compile (which, I think, also has dependencies on GSL being available). This may not be available in older versions of ROOT; I think I’ve had it working with 5.34 and 6.0x.
-Michael
